apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "kafka"
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ORDINAL_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "{{ .Values.kafka.environment.KAFKA_ZOOKEEPER_CONNECT }}"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(POD_NAME).kafka.kafka.svc.cluster.local:9092"
            - name: KAFKA_BROKER_ID
              value: "$(ORDINAL_INDEX)"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "{{ .Values.kafka.environment.KAFKA_AUTO_CREATE_TOPICS_ENABLE }}"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "{{ .Values.kafka.environment.KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR }}"
          ports:
            - containerPort: 9092
              name: kafka
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka
  volumeClaimTemplates:
    - metadata:
        name: kafka-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.kafka.persistence.size }}
        storageClassName: {{ .Values.kafka.persistence.storageClass }}

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.kafka.service.type }}  # This ensures external access
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka
  selector:
    app: kafka
