apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: "{{ .Values.kafkaUI.image.repository }}:{{ .Values.kafkaUI.image.tag }}"
          imagePullPolicy: {{ .Values.kafkaUI.image.pullPolicy }}
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: {{ .Values.kafkaUI.environment.KAFKA_BROKERCONNECT }}

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  ports:
    - port: 9000
  selector:
    app: kafka-ui
  type: {{ .Values.kafkaUI.service.type }}
